server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${host:localhost}:${port:3306}/${database:mitocode}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    username: ${username:root}
    password: ${password:toor}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect #org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    listener:
      concurrency: 1
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      security:
        protocol: ${SECURITY_PROTOCOL:SASL_PLAINTEXT}
      group-id: ${GROUP_ID:pubsub_ssl}
      auto-offset-reset: latest #earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

app:
  topic:
    security_test: ${TOPIC:alumnos_notas}

logging:
  level:
    root: INFO
    "[org.springframework.web]": INFO
    "[org.springframework.kafka]": DEBUG
    "[com.example]": DEBUG